<?php
/**
 * @file
 * Code for the Proud News Display feature.
 */

include_once 'proud_news_display.features.inc';



/**
 * Implements hook_entity_info_alter().
 *
 * Define custom view modes
 */
function proud_news_display_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['featured'] = array(
    'label' => t('Featured'),
    'custom settings' => FALSE,
  );
}



/**
 * Implements hook_panels_pre_render
 */
function proud_news_display_panels_pre_render($panels_display, $renderer) {

  // Are we an article node?
  $article_node = isset($panels_display->context['panelizer']->data->type)
                     && $panels_display->context['panelizer']->data->type == 'article';

  // Article full view
  if($article_node && isset($renderer->address)) {
    menu_tree_set_path('main-menu','news');
  }

  
}